Update pr.yml

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -12,5 +12,5 @@ jobs:
     steps:
     - name: First step 02
       run: echo First step executed
-    - name: Trigger error. Should fail.
-      run: exit 1
+    #- name: Trigger error. Should fail.
+      #run: exit 1
