Update pr.yml

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -2,7 +2,9 @@ name: Test PR and Merge
 
 on:
   pull_request:
-    branches: '*'
+    types: [assigned, opened, synchronize, reopened]
+  push:
+    branches: [master]
 
 jobs:
   job_1:
@@ -11,5 +13,7 @@ jobs:
     steps:
     - name: First step 02
       run: echo First step executed
-    - name: Trigger error. Should fail.
-      run: exit 1
+#     - name: Trigger error. Should fail.
+#       run: exit 1
+    - name: Create tag on successful merging to master
+      run: echo Create tag
